// Kana data for KittyKana
// char entry: [character, romaji, exampleKana, exampleRomaji, exampleEnglish, emoji]
// (example fields optional for dakuten/combo units)

window.KANA_UNITS = [
  // ─── HIRAGANA ───────────────────────────────────────────
  { id:"h1", script:"hiragana", title:"あ Row", subtitle:"a · i · u · e · o", chars:[
    ["あ","a","あり","ari","ant","🐜"],
    ["い","i","いぬ","inu","dog","🐶"],
    ["う","u","うみ","umi","sea","🌊"],
    ["え","e","えんぴつ","enpitsu","pencil","✏️"],
    ["お","o","おにぎり","onigiri","rice ball","🍙"],
  ]},
  { id:"h2", script:"hiragana", title:"か Row", subtitle:"ka · ki · ku · ke · ko", chars:[
    ["か","ka","かさ","kasa","umbrella","☂️"],
    ["き","ki","きつね","kitsune","fox","🦊"],
    ["く","ku","くも","kumo","cloud","☁️"],
    ["け","ke","けむし","kemushi","caterpillar","🐛"],
    ["こ","ko","こねこ","koneko","kitten","🐱"],
  ]},
  { id:"h3", script:"hiragana", title:"さ Row", subtitle:"sa · shi · su · se · so", chars:[
    ["さ","sa","さかな","sakana","fish","🐟"],
    ["し","shi","しっぽ","shippo","tail","🐈"],
    ["す","su","すいか","suika","watermelon","🍉"],
    ["せ","se","せんせい","sensei","teacher","🏫"],
    ["そ","so","そら","sora","sky","🌤️"],
  ]},
  { id:"h4", script:"hiragana", title:"た Row", subtitle:"ta · chi · tsu · te · to", chars:[
    ["た","ta","たまご","tamago","egg","🥚"],
    ["ち","chi","ちず","chizu","map","🗺️"],
    ["つ","tsu","つき","tsuki","moon","🌙"],
    ["て","te","てがみ","tegami","letter","✉️"],
    ["と","to","とり","tori","bird","🐦"],
  ]},
  { id:"h5", script:"hiragana", title:"な Row", subtitle:"na · ni · nu · ne · no", chars:[
    ["な","na","なつ","natsu","summer","☀️"],
    ["に","ni","にくきゅう","nikukyuu","paw pads","🐾"],
    ["ぬ","nu","ぬいぐるみ","nuigurumi","stuffed animal","🧸"],
    ["ね","ne","ねこ","neko","cat","🐱"],
    ["の","no","のり","nori","seaweed","🍙"],
  ]},
  { id:"h6", script:"hiragana", title:"は Row", subtitle:"ha · hi · fu · he · ho", chars:[
    ["は","ha","はな","hana","flower","🌸"],
    ["ひ","hi","ひこうき","hikouki","airplane","✈️"],
    ["ふ","fu","ふね","fune","boat","⛵"],
    ["へ","he","へび","hebi","snake","🐍"],
    ["ほ","ho","ほし","hoshi","star","⭐"],
  ]},
  { id:"h7", script:"hiragana", title:"ま Row", subtitle:"ma · mi · mu · me · mo", chars:[
    ["ま","ma","まど","mado","window","🪟"],
    ["み","mi","みず","mizu","water","💧"],
    ["む","mu","むし","mushi","bug","🐞"],
    ["め","me","めがね","megane","glasses","👓"],
    ["も","mo","もも","momo","peach","🍑"],
  ]},
  { id:"h8", script:"hiragana", title:"や Row", subtitle:"ya · yu · yo", chars:[
    ["や","ya","やま","yama","mountain","⛰️"],
    ["ゆ","yu","ゆき","yuki","snow","❄️"],
    ["よ","yo","よる","yoru","night","🌃"],
  ]},
  { id:"h9", script:"hiragana", title:"ら Row", subtitle:"ra · ri · ru · re · ro", chars:[
    ["ら","ra","らくだ","rakuda","camel","🐫"],
    ["り","ri","りんご","ringo","apple","🍎"],
    ["る","ru","るすばん","rusuban","house-sitting","🏠"],
    ["れ","re","れいぞうこ","reizouko","refrigerator","🧊"],
    ["ろ","ro","ろうそく","rousoku","candle","🕯️"],
  ]},
  { id:"h10", script:"hiragana", title:"わ Row + ん", subtitle:"wa · wo · n", chars:[
    ["わ","wa","わに","wani","crocodile","🐊"],
    ["を","wo","ほんをよむ","hon wo yomu","read a book","📖"],
    ["ん","n","みかん","mikan","mandarin orange","🍊"],
  ]},
  { id:"h11", script:"hiragana", title:"Magic Dots ゛ Part 1", subtitle:"ga · za rows", chars:[
    ["が","ga","がっこう","gakkou","school","🏫"],
    ["ぎ","gi","ぎんいろ","gin'iro","silver","🥈"],
    ["ぐ","gu","ぐるぐる","guruguru","round & round","🌀"],
    ["げ","ge","げんき","genki","energetic","💪"],
    ["ご","go","ごはん","gohan","rice, meal","🍚"],
    ["ざ","za","ざりがに","zarigani","crayfish","🦞"],
    ["じ","ji","じてんしゃ","jitensha","bicycle","🚲"],
    ["ず","zu","ずかん","zukan","picture book","📚"],
    ["ぜ","ze","ぜんぶ","zenbu","everything","💯"],
    ["ぞ","zo","ぞう","zou","elephant","🐘"],
  ]},
  { id:"h12", script:"hiragana", title:"Magic Dots ゛ Part 2", subtitle:"da · ba · pa rows", chars:[
    ["だ","da","だいすき","daisuki","love it!","💖"],
    ["ぢ","ji","はなぢ","hanaji","nosebleed","👃"],
    ["づ","zu","こづつみ","kozutsumi","package","📦"],
    ["で","de","でんしゃ","densha","train","🚃"],
    ["ど","do","どあ","doa","door","🚪"],
    ["ば","ba","ばった","batta","grasshopper","🦗"],
    ["び","bi","びょういん","byouin","hospital","🏥"],
    ["ぶ","bu","ぶどう","budou","grapes","🍇"],
    ["べ","be","べんとう","bentou","lunch box","🍱"],
    ["ぼ","bo","ぼうし","boushi","hat","👒"],
    ["ぱ","pa","ぱんだ","panda","panda","🐼"],
    ["ぴ","pi","ぴかぴか","pikapika","sparkly","✨"],
    ["ぷ","pu","ぷりん","purin","pudding","🍮"],
    ["ぺ","pe","ぺんぎん","pengin","penguin","🐧"],
    ["ぽ","po","ぽけっと","poketto","pocket","👖"],
  ]},
  { id:"h13", script:"hiragana", title:"Combo Sounds 1", subtitle:"kya · sha · cha · nya", chars:[
    ["きゃ","kya"],["きゅ","kyu"],["きょ","kyo"],
    ["しゃ","sha"],["しゅ","shu"],["しょ","sho"],
    ["ちゃ","cha"],["ちゅ","chu"],["ちょ","cho"],
    ["にゃ","nya","にゃんにゃん","nyan nyan","meow meow!","🐱"],["にゅ","nyu"],["にょ","nyo"],
  ]},
  { id:"h14", script:"hiragana", title:"Combo Sounds 2", subtitle:"hya · mya · rya", chars:[
    ["ひゃ","hya"],["ひゅ","hyu"],["ひょ","hyo"],
    ["みゃ","mya"],["みゅ","myu"],["みょ","myo"],
    ["りゃ","rya"],["りゅ","ryu"],["りょ","ryo"],
  ]},
  { id:"h15", script:"hiragana", title:"Combo Sounds 3", subtitle:"gya · ja · bya · pya", chars:[
    ["ぎゃ","gya"],["ぎゅ","gyu"],["ぎょ","gyo"],
    ["じゃ","ja"],["じゅ","ju"],["じょ","jo"],
    ["びゃ","bya"],["びゅ","byu"],["びょ","byo"],
    ["ぴゃ","pya"],["ぴゅ","pyu"],["ぴょ","pyo"],
  ]},

  // ─── KATAKANA ───────────────────────────────────────────
  { id:"k1", script:"katakana", title:"ア Row", subtitle:"a · i · u · e · o", chars:[
    ["ア","a","アイスクリーム","aisukuriimu","ice cream","🍦"],
    ["イ","i","イルカ","iruka","dolphin","🐬"],
    ["ウ","u","ウクレレ","ukurere","ukulele","🎸"],
    ["エ","e","エレベーター","erebeetaa","elevator","🛗"],
    ["オ","o","オレンジ","orenji","orange","🍊"],
  ]},
  { id:"k2", script:"katakana", title:"カ Row", subtitle:"ka · ki · ku · ke · ko", chars:[
    ["カ","ka","カメラ","kamera","camera","📷"],
    ["キ","ki","キウイ","kiui","kiwi","🥝"],
    ["ク","ku","クッキー","kukkii","cookie","🍪"],
    ["ケ","ke","ケーキ","keeki","cake","🍰"],
    ["コ","ko","コアラ","koara","koala","🐨"],
  ]},
  { id:"k3", script:"katakana", title:"サ Row", subtitle:"sa · shi · su · se · so", chars:[
    ["サ","sa","サッカー","sakkaa","soccer","⚽"],
    ["シ","shi","シャワー","shawaa","shower","🚿"],
    ["ス","su","スプーン","supuun","spoon","🥄"],
    ["セ","se","セーター","seetaa","sweater","🧶"],
    ["ソ","so","ソファー","sofaa","sofa","🛋️"],
  ]},
  { id:"k4", script:"katakana", title:"タ Row", subtitle:"ta · chi · tsu · te · to", chars:[
    ["タ","ta","タオル","taoru","towel","🛁"],
    ["チ","chi","チーズ","chiizu","cheese","🧀"],
    ["ツ","tsu","ツナ","tsuna","tuna","🐟"],
    ["テ","te","テレビ","terebi","TV","📺"],
    ["ト","to","トマト","tomato","tomato","🍅"],
  ]},
  { id:"k5", script:"katakana", title:"ナ Row", subtitle:"na · ni · nu · ne · no", chars:[
    ["ナ","na","ナイフ","naifu","knife","🍴"],
    ["ニ","ni","ニュース","nyuusu","news","📰"],
    ["ヌ","nu","ヌードル","nuudoru","noodles","🍜"],
    ["ネ","ne","ネックレス","nekkuresu","necklace","📿"],
    ["ノ","no","ノート","nooto","notebook","📓"],
  ]},
  { id:"k6", script:"katakana", title:"ハ Row", subtitle:"ha · hi · fu · he · ho", chars:[
    ["ハ","ha","ハンバーガー","hanbaagaa","hamburger","🍔"],
    ["ヒ","hi","ヒーロー","hiiroo","hero","🦸"],
    ["フ","fu","フルーツ","furuutsu","fruit","🍓"],
    ["ヘ","he","ヘリコプター","herikoputaa","helicopter","🚁"],
    ["ホ","ho","ホットケーキ","hottokeeki","pancake","🥞"],
  ]},
  { id:"k7", script:"katakana", title:"マ Row", subtitle:"ma · mi · mu · me · mo", chars:[
    ["マ","ma","マンゴー","mangoo","mango","🥭"],
    ["ミ","mi","ミルク","miruku","milk","🥛"],
    ["ム","mu","ムービー","muubii","movie","🎬"],
    ["メ","me","メロン","meron","melon","🍈"],
    ["モ","mo","モンスター","monsutaa","monster","👾"],
  ]},
  { id:"k8", script:"katakana", title:"ヤ Row", subtitle:"ya · yu · yo", chars:[
    ["ヤ","ya","ヤシのき","yashi no ki","palm tree","🌴"],
    ["ユ","yu","ユニコーン","yunikoon","unicorn","🦄"],
    ["ヨ","yo","ヨーヨー","yooyoo","yo-yo","🪀"],
  ]},
  { id:"k9", script:"katakana", title:"ラ Row", subtitle:"ra · ri · ru · re · ro", chars:[
    ["ラ","ra","ライオン","raion","lion","🦁"],
    ["リ","ri","リボン","ribon","ribbon","🎀"],
    ["ル","ru","ルビー","rubii","ruby","💎"],
    ["レ","re","レモン","remon","lemon","🍋"],
    ["ロ","ro","ロボット","robotto","robot","🤖"],
  ]},
  { id:"k10", script:"katakana", title:"ワ Row + ン", subtitle:"wa · wo · n", chars:[
    ["ワ","wa","ワッフル","waffuru","waffle","🧇"],
    ["ヲ","wo","カラオケ","karaoke","karaoke","🎤"],
    ["ン","n","パン","pan","bread","🍞"],
  ]},
  { id:"k11", script:"katakana", title:"Magic Dots ゛ Part 1", subtitle:"ga · za rows", chars:[
    ["ガ","ga","ガム","gamu","gum","🍬"],
    ["ギ","gi","ギター","gitaa","guitar","🎸"],
    ["グ","gu","グミ","gumi","gummy candy","🍬"],
    ["ゲ","ge","ゲーム","geemu","game","🎮"],
    ["ゴ","go","ゴリラ","gorira","gorilla","🦍"],
    ["ザ","za","ピザ","piza","pizza","🍕"],
    ["ジ","ji","ジュース","juusu","juice","🧃"],
    ["ズ","zu","チーズ","chiizu","cheese","🧀"],
    ["ゼ","ze","ゼリー","zerii","jelly","🍮"],
    ["ゾ","zo","ゾンビ","zonbi","zombie","🧟"],
  ]},
  { id:"k12", script:"katakana", title:"Magic Dots ゛ Part 2", subtitle:"da · ba · pa rows", chars:[
    ["ダ","da","ダンス","dansu","dance","💃"],
    ["ヂ","ji"],
    ["ヅ","zu"],
    ["デ","de","デザート","dezaato","dessert","🍨"],
    ["ド","do","ドーナツ","doonatsu","donut","🍩"],
    ["バ","ba","バナナ","banana","banana","🍌"],
    ["ビ","bi","ビーチ","biichi","beach","🏖️"],
    ["ブ","bu","ブーツ","buutsu","boots","👢"],
    ["ベ","be","ベッド","beddo","bed","🛏️"],
    ["ボ","bo","ボール","booru","ball","⚽"],
    ["パ","pa","パンケーキ","pankeeki","pancake","🥞"],
    ["ピ","pi","ピアノ","piano","piano","🎹"],
    ["プ","pu","プール","puuru","pool","🏊"],
    ["ペ","pe","ペン","pen","pen","🖊️"],
    ["ポ","po","ポップコーン","poppukoon","popcorn","🍿"],
  ]},
  { id:"k13", script:"katakana", title:"Combo Sounds 1", subtitle:"kya · sha · cha · nya", chars:[
    ["キャ","kya","キャンディー","kyandii","candy","🍭"],["キュ","kyu"],["キョ","kyo"],
    ["シャ","sha","シャツ","shatsu","shirt","👕"],["シュ","shu"],["ショ","sho"],
    ["チャ","cha","チャンス","chansu","chance","🍀"],["チュ","chu"],["チョ","cho"],
    ["ニャ","nya"],["ニュ","nyu"],["ニョ","nyo"],
  ]},
  { id:"k14", script:"katakana", title:"Combo Sounds 2", subtitle:"hya · mya · rya", chars:[
    ["ヒャ","hya"],["ヒュ","hyu"],["ヒョ","hyo"],
    ["ミャ","mya"],["ミュ","myu"],["ミョ","myo"],
    ["リャ","rya"],["リュ","ryu"],["リョ","ryo"],
  ]},
  { id:"k15", script:"katakana", title:"Combo Sounds 3", subtitle:"gya · ja · bya · pya", chars:[
    ["ギャ","gya"],["ギュ","gyu"],["ギョ","gyo"],
    ["ジャ","ja","ジャム","jamu","jam","🍓"],["ジュ","ju"],["ジョ","jo"],
    ["ビャ","bya"],["ビュ","byu"],["ビョ","byo"],
    ["ピャ","pya"],["ピュ","pyu"],["ピョ","pyo"],
  ]},
];
