// Basic kanji data for KittyKana
window.KANJI = [
// --- Grade 1: numbers ---
{c:"一",m:"one",r:"ichi",kana:"いち",ex:["いちねんせい","ichinensei","first grader"],e:"1️⃣"},
{c:"二",m:"two",r:"ni",kana:"に",ex:["にがつ","nigatsu","February"],e:"2️⃣"},
{c:"三",m:"three",r:"san",kana:"さん",ex:["さんかく","sankaku","triangle"],e:"3️⃣"},
{c:"四",m:"four",r:"yon",kana:"よん",ex:["よんじゅう","yonjuu","forty"],e:"4️⃣"},
{c:"五",m:"five",r:"go",kana:"ご",ex:["ごがつ","gogatsu","May"],e:"5️⃣"},
{c:"六",m:"six",r:"roku",kana:"ろく",ex:["ろくがつ","rokugatsu","June"],e:"6️⃣"},
{c:"七",m:"seven",r:"nana",kana:"なな",ex:["なないろ","nanairo","seven colors, rainbow"],e:"7️⃣"},
{c:"八",m:"eight",r:"hachi",kana:"はち",ex:["はちがつ","hachigatsu","August"],e:"8️⃣"},
{c:"九",m:"nine",r:"kyuu",kana:"きゅう",ex:["きゅうじゅう","kyuujuu","ninety"],e:"9️⃣"},
{c:"十",m:"ten",r:"juu",kana:"じゅう",ex:["じゅうえん","juuen","ten yen"],e:"🔟"},
{c:"百",m:"hundred",r:"hyaku",kana:"ひゃく",ex:["ひゃくてん","hyakuten","perfect score"],e:"💯"},
{c:"千",m:"thousand",r:"sen",kana:"せん",ex:["せんばづる","senbazuru","1000 paper cranes"],e:"🕊️"},
// --- Grade 1: days of the week / elements ---
{c:"日",m:"sun, day",r:"nichi",kana:"にち",ex:["にちようび","nichiyoubi","Sunday"],e:"☀️"},
{c:"月",m:"moon, month",r:"getsu",kana:"げつ",ex:["げつようび","getsuyoubi","Monday"],e:"🌙"},
{c:"火",m:"fire",r:"ka",kana:"か",ex:["かようび","kayoubi","Tuesday"],e:"🔥"},
{c:"水",m:"water",r:"sui",kana:"すい",ex:["すいようび","suiyoubi","Wednesday"],e:"💧"},
{c:"木",m:"tree, wood",r:"moku",kana:"もく",ex:["もくようび","mokuyoubi","Thursday"],e:"🌳"},
{c:"金",m:"gold, money",r:"kin",kana:"きん",ex:["きんようび","kinyoubi","Friday"],e:"🏅"},
{c:"土",m:"earth, soil",r:"do",kana:"ど",ex:["どようび","doyoubi","Saturday"],e:"🟫"},
// --- Grade 1: nature ---
{c:"山",m:"mountain",r:"yama",kana:"やま",ex:["やまのぼり","yamanobori","mountain climbing"],e:"🏔️"},
{c:"川",m:"river",r:"kawa",kana:"かわ",ex:["かわあそび","kawaasobi","playing in the river"],e:"🏞️"},
{c:"田",m:"rice field",r:"ta",kana:"た",ex:["たんぼ","tanbo","rice paddy"],e:"🌾"},
{c:"空",m:"sky",r:"sora",kana:"そら",ex:["そらいろ","sorairo","sky blue"],e:"☁️"},
{c:"雨",m:"rain",r:"ame",kana:"あめ",ex:["あめふり","amefuri","rainy weather"],e:"☔"},
{c:"天",m:"heaven, sky",r:"ten",kana:"てん",ex:["てんき","tenki","weather"],e:"⛅"},
{c:"夕",m:"evening",r:"yuu",kana:"ゆう",ex:["ゆうがた","yuugata","evening"],e:"🌇"},
{c:"石",m:"stone",r:"ishi",kana:"いし",ex:["いしころ","ishikoro","pebble"],e:"🪨"},
{c:"花",m:"flower",r:"hana",kana:"はな",ex:["はなび","hanabi","fireworks"],e:"🌸"},
{c:"草",m:"grass",r:"kusa",kana:"くさ",ex:["くさばな","kusabana","grasses and flowers"],e:"🌿"},
{c:"竹",m:"bamboo",r:"take",kana:"たけ",ex:["たけのこ","takenoko","bamboo shoot"],e:"🎍"},
{c:"林",m:"woods",r:"hayashi",kana:"はやし",ex:["はやし","hayashi","woods"],e:"🌲"},
{c:"森",m:"forest",r:"mori",kana:"もり",ex:["もり","mori","forest"],e:"🌲"},
{c:"虫",m:"bug, insect",r:"mushi",kana:"むし",ex:["むしとり","mushitori","bug catching"],e:"🐛"},
{c:"貝",m:"shellfish, shell",r:"kai",kana:"かい",ex:["かいがら","kaigara","seashell"],e:"🐚"},
{c:"犬",m:"dog",r:"inu",kana:"いぬ",ex:["こいぬ","koinu","puppy"],e:"🐶"},
// --- Grade 1: body ---
{c:"人",m:"person",r:"hito",kana:"ひと",ex:["ひとびと","hitobito","people"],e:"👤"},
{c:"口",m:"mouth",r:"kuchi",kana:"くち",ex:["くちびる","kuchibiru","lips"],e:"👄"},
{c:"目",m:"eye",r:"me",kana:"め",ex:["めだま","medama","eyeball"],e:"👀"},
{c:"耳",m:"ear",r:"mimi",kana:"みみ",ex:["みみたぶ","mimitabu","earlobe"],e:"👂"},
{c:"手",m:"hand",r:"te",kana:"て",ex:["てがみ","tegami","letter"],e:"✋"},
{c:"足",m:"foot, leg",r:"ashi",kana:"あし",ex:["あしあと","ashiato","footprint"],e:"🦶"},
{c:"力",m:"power, strength",r:"chikara",kana:"ちから",ex:["ちからもち","chikaramochi","strong person"],e:"💪"},
// --- Grade 1: people ---
{c:"男",m:"man, male",r:"otoko",kana:"おとこ",ex:["おとこのこ","otokonoko","boy"],e:"👨"},
{c:"女",m:"woman, female",r:"onna",kana:"おんな",ex:["おんなのこ","onnanoko","girl"],e:"👩"},
{c:"子",m:"child",r:"ko",kana:"こ",ex:["こども","kodomo","child"],e:"🧒"},
{c:"王",m:"king",r:"ou",kana:"おう",ex:["おうさま","ousama","king"],e:"👑"},
// --- Grade 1: school and learning ---
{c:"学",m:"study, learning",r:"gaku",kana:"がく",ex:["がくせい","gakusei","student"],e:"📚"},
{c:"校",m:"school",r:"kou",kana:"こう",ex:["がっこう","gakkou","school"],e:"🏫"},
{c:"先",m:"before, ahead",r:"sen",kana:"せん",ex:["せんせい","sensei","teacher"],e:"🧑‍🏫"},
{c:"生",m:"life, birth",r:"sei",kana:"せい",ex:["せいと","seito","student, pupil"],e:"🌱"},
{c:"字",m:"letter, character",r:"ji",kana:"じ",ex:["かんじ","kanji","kanji character"],e:"✍️"},
{c:"文",m:"writing, sentence",r:"bun",kana:"ぶん",ex:["ぶんしょう","bunshou","writing, sentences"],e:"📝"},
{c:"本",m:"book",r:"hon",kana:"ほん",ex:["ほんや","honya","bookstore"],e:"📕"},
{c:"名",m:"name",r:"na",kana:"な",ex:["なまえ","namae","name"],e:"📛"},
{c:"音",m:"sound",r:"on",kana:"おん",ex:["おんがく","ongaku","music"],e:"🎵"},
// --- Grade 1: size and position ---
{c:"大",m:"big",r:"dai",kana:"だい",ex:["だいすき","daisuki","love it a lot"],e:"🐘"},
{c:"小",m:"small",r:"shou",kana:"しょう",ex:["しょうがっこう","shougakkou","elementary school"],e:"🐭"},
{c:"中",m:"middle, inside",r:"naka",kana:"なか",ex:["まんなか","mannaka","the very middle"],e:"🎯"},
{c:"上",m:"up, above",r:"ue",kana:"うえ",ex:["うえ","ue","up, above"],e:"⬆️"},
{c:"下",m:"down, below",r:"shita",kana:"した",ex:["くつした","kutsushita","socks"],e:"⬇️"},
{c:"左",m:"left",r:"hidari",kana:"ひだり",ex:["ひだりて","hidarite","left hand"],e:"⬅️"},
{c:"右",m:"right",r:"migi",kana:"みぎ",ex:["みぎて","migite","right hand"],e:"➡️"},
// --- Grade 1: colors ---
{c:"白",m:"white",r:"shiro",kana:"しろ",ex:["しろくま","shirokuma","polar bear"],e:"🐻‍❄️"},
{c:"赤",m:"red",r:"aka",kana:"あか",ex:["あかちゃん","akachan","baby"],e:"🔴"},
{c:"青",m:"blue",r:"ao",kana:"あお",ex:["あおぞら","aozora","blue sky"],e:"🔵"},
// --- Grade 1: the rest ---
{c:"円",m:"yen, circle",r:"en",kana:"えん",ex:["ひゃくえん","hyakuen","100 yen"],e:"💴"},
{c:"気",m:"spirit, energy",r:"ki",kana:"き",ex:["げんき","genki","healthy, energetic"],e:"😊"},
{c:"休",m:"rest",r:"yasumi",kana:"やすみ",ex:["なつやすみ","natsuyasumi","summer vacation"],e:"🏖️"},
{c:"玉",m:"ball, jewel",r:"tama",kana:"たま",ex:["たまご","tamago","egg"],e:"⚾"},
{c:"見",m:"see, look",r:"mi",kana:"み",ex:["みる","miru","to see"],e:"👁️"},
{c:"糸",m:"thread",r:"ito",kana:"いと",ex:["けいと","keito","yarn"],e:"🧵"},
{c:"車",m:"car, wheel",r:"kuruma",kana:"くるま",ex:["くるま","kuruma","car"],e:"🚗"},
{c:"出",m:"go out, exit",r:"de",kana:"で",ex:["でぐち","deguchi","exit"],e:"📤"},
{c:"正",m:"correct, right",r:"shou",kana:"しょう",ex:["おしょうがつ","oshougatsu","New Year's"],e:"✅"},
{c:"早",m:"early, fast",r:"haya",kana:"はや",ex:["はやおき","hayaoki","early riser"],e:"⏰"},
{c:"村",m:"village",r:"mura",kana:"むら",ex:["むらびと","murabito","villager"],e:"🏘️"},
{c:"町",m:"town",r:"machi",kana:"まち",ex:["まち","machi","town"],e:"🏙️"},
{c:"入",m:"enter, go in",r:"iri",kana:"いり",ex:["いりぐち","iriguchi","entrance"],e:"📥"},
{c:"年",m:"year",r:"nen",kana:"ねん",ex:["いちねん","ichinen","one year"],e:"📅"},
{c:"立",m:"stand up",r:"tatsu",kana:"たつ",ex:["たつ","tatsu","to stand up"],e:"🧍"},
// --- Grade 2: useful picks ---
{c:"何",m:"what",r:"nani",kana:"なに",ex:["なにいろ","naniiro","what color?"],e:"❓"},
{c:"時",m:"time, o'clock",r:"ji",kana:"じ",ex:["さんじ","sanji","three o'clock"],e:"🕒"},
{c:"分",m:"minute, divide",r:"fun",kana:"ふん",ex:["ごふん","gofun","five minutes"],e:"⏱️"},
{c:"今",m:"now",r:"ima",kana:"いま",ex:["いま","ima","now"],e:"⌛"},
{c:"行",m:"go",r:"iku",kana:"いく",ex:["いく","iku","to go"],e:"🚶"},
{c:"来",m:"come",r:"rai",kana:"らい",ex:["らいねん","rainen","next year"],e:"🔜"},
{c:"食",m:"eat",r:"tabe",kana:"たべ",ex:["たべもの","tabemono","food"],e:"🍚"},
{c:"話",m:"talk, story",r:"hanasu",kana:"はなす",ex:["はなす","hanasu","to talk"],e:"💬"},
{c:"読",m:"read",r:"yomu",kana:"よむ",ex:["よむ","yomu","to read"],e:"📖"},
{c:"書",m:"write",r:"kaku",kana:"かく",ex:["かく","kaku","to write"],e:"✏️"},
{c:"買",m:"buy",r:"kai",kana:"かい",ex:["かいもの","kaimono","shopping"],e:"🛒"},
{c:"姉",m:"big sister",r:"nee",kana:"ねえ",ex:["おねえさん","oneesan","big sister"],e:"👧"},
{c:"妹",m:"little sister",r:"imouto",kana:"いもうと",ex:["いもうと","imouto","little sister"],e:"🎀"},
{c:"兄",m:"big brother",r:"nii",kana:"にい",ex:["おにいさん","oniisan","big brother"],e:"👦"},
{c:"弟",m:"little brother",r:"otouto",kana:"おとうと",ex:["おとうと","otouto","little brother"],e:"🧢"},
{c:"朝",m:"morning",r:"asa",kana:"あさ",ex:["あさごはん","asagohan","breakfast"],e:"🌅"},
{c:"昼",m:"noon, daytime",r:"hiru",kana:"ひる",ex:["ひるごはん","hirugohan","lunch"],e:"🌤️"},
{c:"夜",m:"night",r:"yoru",kana:"よる",ex:["よる","yoru","night"],e:"🌃"},
{c:"週",m:"week",r:"shuu",kana:"しゅう",ex:["せんしゅう","senshuu","last week"],e:"🗓️"},
{c:"曜",m:"day of the week",r:"you",kana:"よう",ex:["なんようび","nanyoubi","what day of the week?"],e:"📆"}
];
