// Vocabulary data for KittyKana — [kana, romaji, english, category, emoji]
// Ordered easiest/most essential first; the app teaches 15 per day in array order.
window.VOCAB = [
["ねこ","neko","cat","animals","🐱"],
["いぬ","inu","dog","animals","🐶"],
["こんにちは","konnichiwa","hello","phrases","👋"],
["ありがとう","arigatou","thank you","phrases","💖"],
["おかあさん","okaasan","mom","family","👩"],
["おとうさん","otousan","dad","family","👨"],
["りんご","ringo","apple","food","🍎"],
["バナナ","banana","banana","food","🍌"],
["みず","mizu","water","drinks","💧"],
["ぎゅうにゅう","gyuunyuu","milk","drinks","🥛"],
["あか","aka","red","colors","🔴"],
["あお","ao","blue","colors","🔵"],
["いち","ichi","one","numbers","1️⃣"],
["に","ni","two","numbers","2️⃣"],
["さん","san","three","numbers","3️⃣"],
["よん","yon","four","numbers","4️⃣"],
["ご","go","five","numbers","5️⃣"],
["こねこ","koneko","kitten","animals","🐈"],
["こいぬ","koinu","puppy","animals","🐕"],
["め","me","eye","body","👁️"],
["て","te","hand","body","✋"],
["おはよう","ohayou","good morning","phrases","🌅"],
["はい","hai","yes","phrases","👍"],
["いいえ","iie","no","phrases","👎"],
["ごはん","gohan","rice","food","🍚"],
["パン","pan","bread","food","🍞"],
["たまご","tamago","egg","food","🥚"],
["うさぎ","usagi","rabbit","animals","🐰"],
["とり","tori","bird","animals","🐦"],
["さかな","sakana","fish","animals","🐟"],
["きいろ","kiiro","yellow","colors","🟡"],
["みどり","midori","green","colors","🟢"],
["ろく","roku","six","numbers","6️⃣"],
["なな","nana","seven","numbers","7️⃣"],
["はち","hachi","eight","numbers","8️⃣"],
["きゅう","kyuu","nine","numbers","9️⃣"],
["じゅう","juu","ten","numbers","🔟"],
["たべる","taberu","to eat","verbs","😋"],
["のむ","nomu","to drink","verbs","🥤"],
["みる","miru","to see","verbs","👀"],
["いく","iku","to go","verbs","🚶‍♀️"],
["おおきい","ookii","big","adjectives","🐘"],
["ちいさい","chiisai","small","adjectives","🐭"],
["かわいい","kawaii","cute","adjectives","😻"],
["いえ","ie","house","home","🏠"],
["くるま","kuruma","car","transport","🚗"],
["ほん","hon","book","school","📖"],
["がっこう","gakkou","school","school","🏫"],
["せんせい","sensei","teacher","school","🧑‍🏫"],
["ともだち","tomodachi","friend","school","👭"],
["おはな","ohana","flower","nature","🌼"],
["き","ki","tree","nature","🌳"],
["そら","sora","sky","nature","🌤️"],
["つき","tsuki","moon","nature","🌕"],
["ほし","hoshi","star","nature","⭐"],
["きょう","kyou","today","time","📅"],
["あした","ashita","tomorrow","time","➡️"],
["うみ","umi","sea","sea","🌊"],
["おもちゃ","omocha","toy","fun","🎲"],
["ボール","booru","ball","fun","🏐"],
["ママ","mama","mommy","family","👩‍👧"],
["パパ","papa","daddy","family","👨‍👧"],
["おばあちゃん","obaachan","grandma","family","👵"],
["おじいちゃん","ojiichan","grandpa","family","👴"],
["おねえさん","oneesan","big sister","family","💁‍♀️"],
["おにいさん","oniisan","big brother","family","🙋‍♂️"],
["いもうと","imouto","little sister","family","👧"],
["おとうと","otouto","little brother","family","👦"],
["しろ","shiro","white","colors","⚪"],
["くろ","kuro","black","colors","⚫"],
["ピンク","pinku","pink","colors","🩷"],
["むらさき","murasaki","purple","colors","🟣"],
["オレンジ","orenji","orange","colors","🟠"],
["ちゃいろ","chairo","brown","colors","🟤"],
["みかん","mikan","mandarin orange","food","🍊"],
["いちご","ichigo","strawberry","food","🍓"],
["ぶどう","budou","grapes","food","🍇"],
["もも","momo","peach","food","🍑"],
["すいか","suika","watermelon","food","🍉"],
["おちゃ","ocha","tea","drinks","🍵"],
["ジュース","juusu","juice","drinks","🧃"],
["うま","uma","horse","animals","🐴"],
["うし","ushi","cow","animals","🐮"],
["ぶた","buta","pig","animals","🐷"],
["ひつじ","hitsuji","sheep","animals","🐑"],
["さる","saru","monkey","animals","🐵"],
["くま","kuma","bear","animals","🐻"],
["ぞう","zou","elephant","animals","🐘"],
["きりん","kirin","giraffe","animals","🦒"],
["パンダ","panda","panda","animals","🐼"],
["ライオン","raion","lion","animals","🦁"],
["とら","tora","tiger","animals","🐯"],
["あたま","atama","head","body","👤"],
["かお","kao","face","body","🙂"],
["みみ","mimi","ear","body","👂"],
["はな","hana","nose","body","👃"],
["くち","kuchi","mouth","body","😮"],
["は","ha","tooth","body","🦷"],
["あし","ashi","leg","body","🦵"],
["おなか","onaka","tummy","body","😋"],
["おやすみなさい","oyasuminasai","good night","phrases","🌙"],
["さようなら","sayounara","goodbye","phrases","👋"],
["バイバイ","baibai","bye-bye","phrases","🙋"],
["ごめんなさい","gomennasai","sorry","phrases","🙏"],
["いただきます","itadakimasu","let's eat","phrases","🍽️"],
["ごちそうさま","gochisousama","thanks for food","phrases","🙏"],
["じゅういち","juuichi","eleven","numbers","🔢"],
["じゅうに","juuni","twelve","numbers","🔢"],
["にじゅう","nijuu","twenty","numbers","🔢"],
["ひとつ","hitotsu","one thing","numbers","☝️"],
["ふたつ","futatsu","two things","numbers","✌️"],
["みっつ","mittsu","three things","numbers","🤟"],
["チーズ","chiizu","cheese","food","🧀"],
["ケーキ","keeki","cake","food","🍰"],
["アイスクリーム","aisukuriimu","ice cream","food","🍦"],
["クッキー","kukkii","cookie","food","🍪"],
["チョコレート","chokoreeto","chocolate","food","🍫"],
["あるく","aruku","to walk","verbs","🚶"],
["はしる","hashiru","to run","verbs","🏃"],
["とぶ","tobu","to jump","verbs","🦘"],
["うたう","utau","to sing","verbs","🎤"],
["およぐ","oyogu","to swim","verbs","🏊"],
["あそぶ","asobu","to play","verbs","🪀"],
["たのしい","tanoshii","fun","adjectives","🎉"],
["おいしい","oishii","yummy","adjectives","🤤"],
["うれしい","ureshii","happy","adjectives","😊"],
["かなしい","kanashii","sad","adjectives","😢"],
["でんしゃ","densha","train","transport","🚃"],
["バス","basu","bus","transport","🚌"],
["じてんしゃ","jitensha","bicycle","transport","🚲"],
["ひこうき","hikouki","airplane","transport","✈️"],
["えんぴつ","enpitsu","pencil","school","✏️"],
["ノート","nooto","notebook","school","📓"],
["つくえ","tsukue","desk","school","🪑"],
["いす","isu","chair","school","💺"],
["かぞく","kazoku","family","family","👨‍👩‍👧"],
["あかちゃん","akachan","baby","family","👶"],
["ドア","doa","door","home","🚪"],
["まど","mado","window","home","🪟"],
["ベッド","beddo","bed","home","🛏️"],
["テレビ","terebi","TV","home","📺"],
["でんわ","denwa","telephone","home","📞"],
["とけい","tokei","clock","home","⏰"],
["てんき","tenki","weather","weather","🌦️"],
["はれ","hare","sunny","weather","☀️"],
["あめ","ame","rain","weather","🌧️"],
["くも","kumo","cloud","weather","☁️"],
["ゆき","yuki","snow","weather","❄️"],
["かぜ","kaze","wind","weather","🌬️"],
["にじ","niji","rainbow","weather","🌈"],
["かさ","kasa","umbrella","weather","☔"],
["ふく","fuku","clothes","clothes","👚"],
["シャツ","shatsu","shirt","clothes","👕"],
["ズボン","zubon","pants","clothes","👖"],
["スカート","sukaato","skirt","clothes","👗"],
["くつ","kutsu","shoes","clothes","👟"],
["くつした","kutsushita","socks","clothes","🧦"],
["ぼうし","boushi","hat","clothes","👒"],
["いま","ima","now","time","🕐"],
["あさ","asa","morning","time","🌅"],
["ひる","hiru","daytime","time","🌞"],
["よる","yoru","night","time","🌃"],
["きのう","kinou","yesterday","time","⬅️"],
["こうえん","kouen","park","town","⛲"],
["みせ","mise","store","town","🛍️"],
["どうぶつえん","doubutsuen","zoo","town","🦓"],
["ねずみ","nezumi","mouse","animals","🐭"],
["かえる","kaeru","frog","animals","🐸"],
["かめ","kame","turtle","animals","🐢"],
["へび","hebi","snake","animals","🐍"],
["にわとり","niwatori","chicken","animals","🐔"],
["あひる","ahiru","duck","animals","🦆"],
["ちょうちょ","choucho","butterfly","animals","🦋"],
["みつばち","mitsubachi","honeybee","animals","🐝"],
["あり","ari","ant","animals","🐜"],
["だいすき","daisuki","love it","phrases","😍"],
["すごい","sugoi","wow","phrases","🤩"],
["やった","yatta","yay","phrases","🙌"],
["おなかがすいた","onaka ga suita","I'm hungry","phrases","🍴"],
["のどがかわいた","nodo ga kawaita","I'm thirsty","phrases","🥤"],
["ただいま","tadaima","I'm home","phrases","🏠"],
["おかえり","okaeri","welcome back","phrases","🤗"],
["いってきます","ittekimasu","I'm off","phrases","👋"],
["いってらっしゃい","itterasshai","take care","phrases","🙋‍♀️"],
["よっつ","yottsu","four things","numbers","🔢"],
["いつつ","itsutsu","five things","numbers","🔢"],
["むっつ","muttsu","six things","numbers","🔢"],
["ななつ","nanatsu","seven things","numbers","🔢"],
["やっつ","yattsu","eight things","numbers","🔢"],
["ここのつ","kokonotsu","nine things","numbers","🔢"],
["とお","too","ten things","numbers","🔢"],
["ひゃく","hyaku","hundred","numbers","💯"],
["せん","sen","thousand","numbers","🔢"],
["にんじん","ninjin","carrot","food","🥕"],
["じゃがいも","jagaimo","potato","food","🥔"],
["たまねぎ","tamanegi","onion","food","🧅"],
["トマト","tomato","tomato","food","🍅"],
["きゅうり","kyuuri","cucumber","food","🥒"],
["かぼちゃ","kabocha","pumpkin","food","🎃"],
["とうもろこし","toumorokoshi","corn","food","🌽"],
["おにぎり","onigiri","rice ball","food","🍙"],
["すし","sushi","sushi","food","🍣"],
["ラーメン","raamen","ramen","food","🍜"],
["うどん","udon","udon noodles","food","🍜"],
["カレー","karee","curry","food","🍛"],
["ピザ","piza","pizza","food","🍕"],
["ハンバーガー","hanbaagaa","hamburger","food","🍔"],
["サンドイッチ","sandoitchi","sandwich","food","🥪"],
["スープ","suupu","soup","food","🥣"],
["サラダ","sarada","salad","food","🥗"],
["あまい","amai","sweet","adjectives","🍬"],
["からい","karai","spicy","adjectives","🌶️"],
["すっぱい","suppai","sour","adjectives","🍋"],
["たかい","takai","tall","adjectives","⬆️"],
["ひくい","hikui","low","adjectives","⬇️"],
["ながい","nagai","long","adjectives","📏"],
["みじかい","mijikai","short","adjectives","🤏"],
["あつい","atsui","hot","adjectives","🥵"],
["さむい","samui","cold","adjectives","🥶"],
["あたたかい","atatakai","warm","adjectives","♨️"],
["すずしい","suzushii","cool","adjectives","🍃"],
["つめたい","tsumetai","icy cold","adjectives","🧊"],
["きく","kiku","to listen","verbs","👂"],
["はなす","hanasu","to speak","verbs","🗣️"],
["よむ","yomu","to read","verbs","📖"],
["かく","kaku","to write","verbs","✍️"],
["くる","kuru","to come","verbs","👣"],
["おきる","okiru","to wake up","verbs","⏰"],
["ねる","neru","to sleep","verbs","😴"],
["すわる","suwaru","to sit","verbs","🧘"],
["たつ","tatsu","to stand","verbs","🧍"],
["わらう","warau","to laugh","verbs","😆"],
["なく","naku","to cry","verbs","😭"],
["ゆび","yubi","finger","body","☝️"],
["かみのけ","kaminoke","hair","body","💇"],
["かた","kata","shoulder","body","🤷"],
["ひざ","hiza","knee","body","🦵"],
["うで","ude","arm","body","💪"],
["くび","kubi","neck","body","🦒"],
["ほっぺ","hoppe","cheek","body","☺️"],
["ランドセル","randoseru","school backpack","school","🎒"],
["けしゴム","keshigomu","eraser","school","🧽"],
["はさみ","hasami","scissors","school","✂️"],
["のり","nori","glue","school","🧴"],
["クレヨン","kureyon","crayon","school","🖍️"],
["いろえんぴつ","iroenpitsu","colored pencils","school","🌈"],
["え","e","picture","school","🖼️"],
["かみ","kami","paper","school","📄"],
["ぬいぐるみ","nuigurumi","stuffed animal","fun","🧸"],
["にんぎょう","ningyou","doll","fun","🪆"],
["ブランコ","buranko","swing","fun","🎠"],
["すべりだい","suberidai","slide","fun","🛝"],
["シーソー","shiisoo","seesaw","fun","⚖️"],
["なわとび","nawatobi","jump rope","fun","🪢"],
["かくれんぼ","kakurenbo","hide and seek","fun","🙈"],
["おにごっこ","onigokko","tag","fun","🏃"],
["じゃんけん","janken","rock paper scissors","fun","✊"],
["サッカー","sakkaa","soccer","fun","⚽"],
["やきゅう","yakyuu","baseball","fun","⚾"],
["うた","uta","song","fun","🎵"],
["おんがく","ongaku","music","fun","🎶"],
["ピアノ","piano","piano","fun","🎹"],
["へや","heya","room","home","🛌"],
["だいどころ","daidokoro","kitchen","home","🍳"],
["おふろ","ofuro","bath","home","🛁"],
["トイレ","toire","toilet","home","🚽"],
["にわ","niwa","yard","home","🏡"],
["ゆか","yuka","floor","home","🪵"],
["かべ","kabe","wall","home","🧱"],
["やね","yane","roof","home","🏠"],
["まくら","makura","pillow","home","🛌"],
["もうふ","moufu","blanket","home","🛏️"],
["ふとん","futon","futon","home","🛌"],
["テーブル","teeburu","table","home","🍽️"],
["ソファ","sofa","sofa","home","🛋️"],
["コップ","koppu","cup","home","🫗"],
["おさら","osara","plate","home","🍽️"],
["はし","hashi","chopsticks","home","🥢"],
["スプーン","supuun","spoon","home","🥄"],
["フォーク","fooku","fork","home","🍴"],
["タオル","taoru","towel","home","🧺"],
["はぶらし","haburashi","toothbrush","home","🪥"],
["かがみ","kagami","mirror","home","🪞"],
["でんき","denki","light","home","💡"],
["スーパー","suupaa","supermarket","town","🛒"],
["コンビニ","konbini","convenience store","town","🏪"],
["パンや","panya","bakery","town","🥐"],
["ほんや","honya","bookstore","town","📚"],
["はなや","hanaya","flower shop","town","💐"],
["レストラン","resutoran","restaurant","town","🧑‍🍳"],
["びょういん","byouin","hospital","town","🏥"],
["ゆうびんきょく","yuubinkyoku","post office","town","📮"],
["ぎんこう","ginkou","bank","town","🏦"],
["みち","michi","road","town","🛣️"],
["しんごう","shingou","traffic light","town","🚦"],
["えき","eki","train station","transport","🚉"],
["タクシー","takushii","taxi","transport","🚕"],
["ふね","fune","boat","transport","⛵"],
["しんかんせん","shinkansen","bullet train","transport","🚄"],
["ちかてつ","chikatetsu","subway","transport","🚇"],
["トラック","torakku","truck","transport","🚚"],
["パトカー","patokaa","police car","transport","🚓"],
["しょうぼうしゃ","shoubousha","fire truck","transport","🚒"],
["きゅうきゅうしゃ","kyuukyuusha","ambulance","transport","🚑"],
["ヘリコプター","herikoputaa","helicopter","transport","🚁"],
["ロケット","roketto","rocket","transport","🚀"],
["げつようび","getsuyoubi","Monday","time","🌙"],
["かようび","kayoubi","Tuesday","time","🔥"],
["すいようび","suiyoubi","Wednesday","time","💧"],
["もくようび","mokuyoubi","Thursday","time","🌳"],
["きんようび","kinyoubi","Friday","time","✨"],
["どようび","doyoubi","Saturday","time","🪨"],
["にちようび","nichiyoubi","Sunday","time","☀️"],
["はる","haru","spring","time","🌸"],
["なつ","natsu","summer","time","⛱️"],
["あき","aki","fall","time","🍂"],
["ふゆ","fuyu","winter","time","☃️"],
["イルカ","iruka","dolphin","sea","🐬"],
["クジラ","kujira","whale","sea","🐳"],
["サメ","same","shark","sea","🦈"],
["タコ","tako","octopus","sea","🐙"],
["カニ","kani","crab","sea","🦀"],
["エビ","ebi","shrimp","sea","🦐"],
["イカ","ika","squid","sea","🦑"],
["なみ","nami","wave","sea","🌊"],
["かいがら","kaigara","seashell","sea","🐚"],
["はまべ","hamabe","beach","sea","🏖️"],
["ヒトデ","hitode","starfish","sea","⭐"],
["クラゲ","kurage","jellyfish","sea","🪼"],
["きつね","kitsune","fox","animals","🦊"],
["たぬき","tanuki","raccoon dog","animals","🦝"],
["しか","shika","deer","animals","🦌"],
["りす","risu","squirrel","animals","🐿️"],
["ふくろう","fukurou","owl","animals","🦉"],
["ペンギン","pengin","penguin","animals","🐧"],
["コアラ","koara","koala","animals","🐨"],
["カンガルー","kangaruu","kangaroo","animals","🦘"],
["ハムスター","hamusutaa","hamster","animals","🐹"],
["にくきゅう","nikukyuu","paw pads","animals","🐾"],
["しっぽ","shippo","tail","animals","🐈"],
["ひげ","hige","whiskers","animals","🐈‍⬛"],
["やぎ","yagi","goat","animals","🐐"],
["おおかみ","ookami","wolf","animals","🐺"],
["かたつむり","katatsumuri","snail","animals","🐌"],
["バッタ","batta","grasshopper","animals","🦗"],
["てんとうむし","tentoumushi","ladybug","animals","🐞"],
["かぶとむし","kabutomushi","beetle","animals","🪲"],
["メロン","meron","melon","food","🍈"],
["レモン","remon","lemon","food","🍋"],
["さくらんぼ","sakuranbo","cherry","food","🍒"],
["パイナップル","painappuru","pineapple","food","🍍"],
["ブロッコリー","burokkorii","broccoli","food","🥦"],
["レタス","retasu","lettuce","food","🥬"],
["きのこ","kinoko","mushroom","food","🍄"],
["にく","niku","meat","food","🍖"],
["とりにく","toriniku","chicken meat","food","🍗"],
["ぎゅうにく","gyuuniku","beef","food","🥩"],
["ぶたにく","butaniku","pork","food","🥓"],
["ソーセージ","sooseeji","sausage","food","🌭"],
["バター","bataa","butter","food","🧈"],
["そば","soba","soba noodles","food","🍜"],
["やきそば","yakisoba","fried noodles","food","🍝"],
["みそしる","misoshiru","miso soup","food","🍲"],
["おべんとう","obentou","lunch box","food","🍱"],
["おかし","okashi","sweets","food","🍭"],
["キャンディー","kyandii","candy","food","🍬"],
["ドーナツ","doonatsu","donut","food","🍩"],
["プリン","purin","pudding","food","🍮"],
["ポップコーン","poppukoon","popcorn","food","🍿"],
["せんべい","senbei","rice cracker","food","🍘"],
["ココア","kokoa","cocoa","drinks","🍫"],
["コーヒー","koohii","coffee","drinks","☕"],
["こうちゃ","koucha","black tea","drinks","🫖"],
["むぎちゃ","mugicha","barley tea","drinks","🍵"],
["オレンジジュース","orenjijuusu","orange juice","drinks","🧃"],
["レモネード","remoneedo","lemonade","drinks","🥤"],
["ソーダ","sooda","soda","drinks","🥤"],
["スムージー","sumuujii","smoothie","drinks","🫐"],
["はいいろ","haiiro","gray","colors","🩶"],
["きんいろ","kiniro","gold","colors","🥇"],
["ぎんいろ","giniro","silver","colors","🥈"],
["みずいろ","mizuiro","light blue","colors","🩵"],
["おばさん","obasan","aunt","family","👩"],
["おじさん","ojisan","uncle","family","👨"],
["いとこ","itoko","cousin","family","🧒"],
["りょうしん","ryoushin","parents","family","👫"],
["きょうだい","kyoudai","siblings","family","🧑‍🤝‍🧑"],
["ふたご","futago","twins","family","👯"],
["せなか","senaka","back","body","🧍"],
["おでこ","odeko","forehead","body","😶"],
["くちびる","kuchibiru","lips","body","👄"],
["つめ","tsume","nail","body","💅"],
["ひじ","hiji","elbow","body","💪"],
["セーター","seetaa","sweater","clothes","🧶"],
["コート","kooto","coat","clothes","🧥"],
["ジャケット","jaketto","jacket","clothes","🧥"],
["ワンピース","wanpiisu","dress","clothes","👗"],
["パジャマ","pajama","pajamas","clothes","😴"],
["みずぎ","mizugi","swimsuit","clothes","🩱"],
["てぶくろ","tebukuro","gloves","clothes","🧤"],
["マフラー","mafuraa","scarf","clothes","🧣"],
["めがね","megane","glasses","clothes","👓"],
["ポケット","poketto","pocket","clothes","👖"],
["ボタン","botan","button","clothes","🔘"],
["ペン","pen","pen","school","🖊️"],
["こくばん","kokuban","blackboard","school","🟩"],
["きょうしつ","kyoushitsu","classroom","school","🏫"],
["じょうぎ","jougi","ruler","school","📏"],
["テスト","tesuto","test","school","✅"],
["しゅくだい","shukudai","homework","school","📝"],
["としょかん","toshokan","library","school","📚"],
["やすみじかん","yasumijikan","recess","school","🤸"],
["きゅうしょく","kyuushoku","school lunch","school","🍱"],
["ひらがな","hiragana","hiragana","school","🔤"],
["かたかな","katakana","katakana","school","🔤"],
["かんじ","kanji","kanji","school","🈶"],
["にほんご","nihongo","Japanese","school","🇯🇵"],
["えいご","eigo","English","school","🇺🇸"],
["やま","yama","mountain","nature","⛰️"],
["かわ","kawa","river","nature","🏞️"],
["はっぱ","happa","leaf","nature","🌿"],
["くさ","kusa","grass","nature","☘️"],
["もり","mori","forest","nature","🌲"],
["いし","ishi","stone","nature","🪨"],
["すな","suna","sand","nature","⏳"],
["みずうみ","mizuumi","lake","nature","🏞️"],
["いけ","ike","pond","nature","🪷"],
["たき","taki","waterfall","nature","💦"],
["たね","tane","seed","nature","🌱"],
["さくら","sakura","cherry blossom","nature","🌸"],
["ひまわり","himawari","sunflower","nature","🌻"],
["ばら","bara","rose","nature","🌹"],
["たんぽぽ","tanpopo","dandelion","nature","🌼"],
["チューリップ","chuurippu","tulip","nature","🌷"],
["たけ","take","bamboo","nature","🎋"],
["どんぐり","donguri","acorn","nature","🌰"],
["しぜん","shizen","nature","nature","🍃"],
["のはら","nohara","meadow","nature","🌾"],
["おか","oka","hill","nature","🌄"],
["どろ","doro","mud","nature","🟤"],
["たいよう","taiyou","sun","nature","☀️"],
["くもり","kumori","cloudy","weather","🌥️"],
["かみなり","kaminari","thunder","weather","⚡"],
["たいふう","taifuu","typhoon","weather","🌀"],
["きり","kiri","fog","weather","🌫️"],
["あらし","arashi","storm","weather","⛈️"],
["つゆ","tsuyu","rainy season","weather","🌧️"],
["こおり","koori","ice","weather","🧊"],
["ゆきだるま","yukidaruma","snowman","weather","⛄"],
["いう","iu","to say","verbs","💬"],
["かう","kau","to buy","verbs","🛒"],
["つくる","tsukuru","to make","verbs","🔨"],
["あける","akeru","to open","verbs","🔓"],
["しめる","shimeru","to close","verbs","🔒"],
["いれる","ireru","to put in","verbs","📥"],
["だす","dasu","to take out","verbs","📤"],
["もつ","motsu","to hold","verbs","🤲"],
["あげる","ageru","to give","verbs","🎁"],
["もらう","morau","to get","verbs","🫴"],
["おしえる","oshieru","to teach","verbs","🧑‍🏫"],
["ならう","narau","to learn","verbs","🎓"],
["べんきょうする","benkyousuru","to study","verbs","📚"],
["おぼえる","oboeru","to remember","verbs","🧠"],
["わすれる","wasureru","to forget","verbs","💭"],
["あらう","arau","to wash","verbs","🧼"],
["そうじする","soujisuru","to clean","verbs","🧹"],
["てつだう","tetsudau","to help","verbs","🤝"],
["まつ","matsu","to wait","verbs","⏳"],
["さがす","sagasu","to look for","verbs","🔍"],
["みつける","mitsukeru","to find","verbs","🔎"],
["つかう","tsukau","to use","verbs","🔧"],
["きる","kiru","to cut","verbs","✂️"],
["のぼる","noboru","to climb","verbs","🧗"],
["おりる","oriru","to go down","verbs","⬇️"],
["なげる","nageru","to throw","verbs","🤾"],
["ける","keru","to kick","verbs","🦵"],
["とる","toru","to take","verbs","🫳"],
["つかまえる","tsukamaeru","to catch","verbs","🦋"],
["さわる","sawaru","to touch","verbs","👉"],
["かくれる","kakureru","to hide","verbs","🙈"],
["おす","osu","to push","verbs","🫸"],
["もどる","modoru","to go back","verbs","↩️"],
["おどる","odoru","to dance","verbs","💃"],
["いい","ii","good","adjectives","👍"],
["わるい","warui","bad","adjectives","👎"],
["はやい","hayai","fast","adjectives","🐆"],
["おそい","osoi","slow","adjectives","🐢"],
["あたらしい","atarashii","new","adjectives","✨"],
["ふるい","furui","old","adjectives","🏚️"],
["まずい","mazui","yucky","adjectives","🤢"],
["にがい","nigai","bitter","adjectives","😖"],
["しょっぱい","shoppai","salty","adjectives","🧂"],
["こわい","kowai","scary","adjectives","👻"],
["おもしろい","omoshiroi","funny","adjectives","🤣"],
["つまらない","tsumaranai","boring","adjectives","🥱"],
["きれい","kirei","pretty","adjectives","🌺"],
["かっこいい","kakkoii","cool","adjectives","😎"],
["やさしい","yasashii","kind","adjectives","🥰"],
["つよい","tsuyoi","strong","adjectives","💪"],
["よわい","yowai","weak","adjectives","🥀"],
["おもい","omoi","heavy","adjectives","🏋️"],
["かるい","karui","light","adjectives","🪶"],
["あかるい","akarui","bright","adjectives","🔆"],
["くらい","kurai","dark","adjectives","🌑"],
["しずか","shizuka","quiet","adjectives","🤫"],
["うるさい","urusai","noisy","adjectives","📢"],
["いそがしい","isogashii","busy","adjectives","😵‍💫"],
["ねむい","nemui","sleepy","adjectives","😪"],
["げんき","genki","cheerful","adjectives","😄"],
["どういたしまして","douitashimashite","you're welcome","phrases","😊"],
["すみません","sumimasen","excuse me","phrases","🙇"],
["おねがいします","onegaishimasu","please","phrases","🙏"],
["こんばんは","konbanwa","good evening","phrases","🌆"],
["じゃあね","jaane","see you","phrases","👋"],
["がんばって","ganbatte","good luck","phrases","📣"],
["おめでとう","omedetou","congratulations","phrases","🥳"],
["たんじょうびおめでとう","tanjoubi omedetou","happy birthday","phrases","🎂"],
["だいじょうぶ","daijoubu","it's okay","phrases","👌"],
["たすけて","tasukete","help!","phrases","🆘"],
["もういっかい","mou ikkai","one more time","phrases","🔁"],
["ちょっとまって","chotto matte","wait a second","phrases","⏸️"],
["どうぞ","douzo","here you go","phrases","🎀"],
["かんぱい","kanpai","cheers","phrases","🥂"],
["おなまえは","onamae wa","what's your name","phrases","📛"],
["げんかん","genkan","entryway","home","🚪"],
["まち","machi","town","town","🏘️"],
["けいさつ","keisatsu","police","town","👮"],
["しょうぼうしょ","shoubousho","fire station","town","🧑‍🚒"],
["ゆうえんち","yuuenchi","amusement park","town","🎡"],
["すいぞくかん","suizokukan","aquarium","town","🐠"],
["えいがかん","eigakan","movie theater","town","🎬"],
["はくぶつかん","hakubutsukan","museum","town","🏛️"],
["おてら","otera","temple","town","🔔"],
["じんじゃ","jinja","shrine","town","⛩️"],
["ホテル","hoteru","hotel","town","🏨"],
["デパート","depaato","department store","town","🏬"],
["テニス","tenisu","tennis","fun","🎾"],
["バスケットボール","basukettobooru","basketball","fun","🏀"],
["すいえい","suiei","swimming","fun","🏊"],
["ダンス","dansu","dance","fun","🩰"],
["ゲーム","geemu","video game","fun","🎮"],
["カード","kaado","card","fun","🃏"],
["パズル","pazuru","puzzle","fun","🧩"],
["つみき","tsumiki","building blocks","fun","🧱"],
["ギター","gitaa","guitar","fun","🎸"],
["たいこ","taiko","drum","fun","🥁"],
["まんが","manga","comic book","fun","📕"],
["アニメ","anime","anime","fun","📺"],
["えいが","eiga","movie","fun","🎥"],
["おえかき","oekaki","drawing","fun","🎨"],
["おりがみ","origami","origami","fun","🦢"],
["シール","shiiru","sticker","fun","🌟"],
["ふうせん","fuusen","balloon","fun","🎈"],
["プレゼント","purezento","present","fun","🎁"],
["たんじょうび","tanjoubi","birthday","fun","🎂"],
["おまつり","omatsuri","festival","fun","🏮"],
["はなび","hanabi","fireworks","fun","🎆"],
["いちがつ","ichigatsu","January","time","🎍"],
["にがつ","nigatsu","February","time","💝"],
["じかん","jikan","time","time","🕰️"],
["しゅうまつ","shuumatsu","weekend","time","🥳"],
["まいにち","mainichi","every day","time","📆"],
["ゆうがた","yuugata","evening","time","🌇"],
["らいしゅう","raishuu","next week","time","🗓️"],
["ラッコ","rakko","sea otter","sea","🦦"],
["アザラシ","azarashi","seal","sea","🦭"],
// --- Extended set: later-in-the-year words ---
["これ","kore","this","phrases","👇"],
["それ","sore","that","phrases","👉"],
["あれ","are","that over there","phrases","🔭"],
["ここ","koko","here","phrases","📍"],
["そこ","soko","there","phrases","👉"],
["どこ","doko","where","phrases","🗺️"],
["だれ","dare","who","phrases","👤"],
["なに","nani","what","phrases","❓"],
["いつ","itsu","when","phrases","📅"],
["なんで","nande","why","phrases","🤷"],
["どっち","dotchi","which one","phrases","🔀"],
["すき","suki","like","adjectives","💕"],
["きらい","kirai","dislike","adjectives","💔"],
["いたい","itai","ouchy","adjectives","🤕"],
["かゆい","kayui","itchy","adjectives","🦟"],
["はずかしい","hazukashii","embarrassed","adjectives","😳"],
["さびしい","sabishii","lonely","adjectives","🥺"],
["ゼロ","zero","zero","numbers","0️⃣"],
["さんじゅう","sanjuu","thirty","numbers","🔢"],
["よんじゅう","yonjuu","forty","numbers","🔢"],
["ごじゅう","gojuu","fifty","numbers","🔢"],
["ろくじゅう","rokujuu","sixty","numbers","🔢"],
["ななじゅう","nanajuu","seventy","numbers","🔢"],
["はちじゅう","hachijuu","eighty","numbers","🔢"],
["きゅうじゅう","kyuujuu","ninety","numbers","🔢"],
["いちまん","ichiman","ten thousand","numbers","🔢"],
["さんがつ","sangatsu","March","time","🎎"],
["しがつ","shigatsu","April","time","🌸"],
["ごがつ","gogatsu","May","time","🎏"],
["ろくがつ","rokugatsu","June","time","🌧️"],
["しちがつ","shichigatsu","July","time","🎋"],
["はちがつ","hachigatsu","August","time","🌻"],
["くがつ","kugatsu","September","time","🌕"],
["じゅうがつ","juugatsu","October","time","🎃"],
["じゅういちがつ","juuichigatsu","November","time","🍂"],
["じゅうにがつ","juunigatsu","December","time","🎄"],
["さんすう","sansuu","math","school","➕"],
["こくご","kokugo","Japanese class","school","📖"],
["りか","rika","science","school","🔬"],
["しゃかい","shakai","social studies","school","🗺️"],
["たいいく","taiiku","P.E.","school","🤸"],
["ずこう","zukou","arts and crafts","school","🎨"],
["わかる","wakaru","to understand","verbs","💡"],
["しる","shiru","to know","verbs","🧠"],
["できる","dekiru","can do","verbs","🙆"],
["がんばる","ganbaru","to try hard","verbs","💪"],
["はいる","hairu","to enter","verbs","🚪"],
["でる","deru","to go out","verbs","🚶"],
["のる","noru","to ride","verbs","🚌"],
["あう","au","to meet","verbs","🤝"],
["つく","tsuku","to arrive","verbs","📍"],
["はじめる","hajimeru","to start","verbs","▶️"],
["おわる","owaru","to finish","verbs","⏹️"],
["とまる","tomaru","to stop","verbs","🛑"],
["てんぷら","tenpura","tempura","food","🍤"],
["からあげ","karaage","fried chicken","food","🍗"],
["ぎょうざ","gyouza","dumplings","food","🥟"],
["たこやき","takoyaki","octopus balls","food","🐙"],
["やきとり","yakitori","chicken skewers","food","🍢"],
["おこのみやき","okonomiyaki","savory pancake","food","🥞"],
["とんかつ","tonkatsu","pork cutlet","food","🍱"],
["オムライス","omuraisu","omelet rice","food","🍳"],
["チャーハン","chaahan","fried rice","food","🍚"],
["パンケーキ","pankeeki","pancake","food","🥞"],
["ホットドッグ","hottodoggu","hot dog","food","🌭"],
["フライドポテト","furaidopoteto","french fries","food","🍟"],
["ゴリラ","gorira","gorilla","animals","🦍"],
["シマウマ","shimauma","zebra","animals","🦓"],
["カバ","kaba","hippo","animals","🦛"],
["サイ","sai","rhino","animals","🦏"],
["ラクダ","rakuda","camel","animals","🐫"],
["ワニ","wani","crocodile","animals","🐊"],
["コウモリ","koumori","bat","animals","🦇"],
["ハリネズミ","harinezumi","hedgehog","animals","🦔"],
["ナマケモノ","namakemono","sloth","animals","🦥"],
["フラミンゴ","furamingo","flamingo","animals","🦩"],
["クジャク","kujaku","peacock","animals","🦚"],
["オウム","oumu","parrot","animals","🦜"],
["のど","nodo","throat","body","🗣️"],
["した","shita","tongue","body","👅"],
["ほね","hone","bone","body","🦴"],
["おへそ","oheso","belly button","body","🔘"],
["まゆげ","mayuge","eyebrow","body","🤨"],
["まつげ","matsuge","eyelashes","body","👁️"],
["こし","koshi","waist","body","🧍"],
["かかと","kakato","heel","body","🦶"],
["えがお","egao","smile","body","😁"],
["ちから","chikara","strength","body","💪"],
["とても","totemo","very","phrases","❗"],
["すこし","sukoshi","a little","phrases","🤏"],
["ちょっと","chotto","a bit","phrases","☝️"],
["たくさん","takusan","a lot","phrases","💯"],
["いっぱい","ippai","lots","phrases","🈵"],
["みんな","minna","everyone","phrases","🧑‍🤝‍🧑"],
["いっしょに","issho ni","together","phrases","🤝"],
["また","mata","again","phrases","🔁"],
["もっと","motto","more","phrases","➕"],
["すぐ","sugu","right away","phrases","⚡"],
["ゆっくり","yukkuri","slowly","phrases","🐢"],
["はやく","hayaku","quickly","phrases","💨"],
["いつも","itsumo","always","phrases","🔁"],
["ときどき","tokidoki","sometimes","phrases","🎲"],
["たぶん","tabun","maybe","phrases","🤷"],
["ぜんぶ","zenbu","everything","phrases","✅"],
["つける","tsukeru","to turn on","verbs","💡"],
["けす","kesu","to turn off","verbs","🔌"],
["れんしゅうする","renshuusuru","to practice","verbs","🎯"],
["うんどうする","undousuru","to exercise","verbs","🏋️"],
["さんぽする","sanposuru","to take a walk","verbs","🚶"],
["かりる","kariru","to borrow","verbs","🤲"],
["かえす","kaesu","to give back","verbs","↩️"],
["おくる","okuru","to send","verbs","✉️"],
["えらぶ","erabu","to choose","verbs","👉"],
["きめる","kimeru","to decide","verbs","✅"],
["ひろう","hirou","to pick up","verbs","🫳"],
["すてる","suteru","to throw away","verbs","🗑️"],
["いしゃ","isha","doctor","town","🧑‍⚕️"],
["はいしゃ","haisha","dentist","town","🦷"],
["じゅうい","juui","vet","town","🩺"],
["かんごし","kangoshi","nurse","town","💉"],
["けいさつかん","keisatsukan","police officer","town","👮"],
["しょうぼうし","shouboushi","firefighter","town","🧑‍🚒"],
["うんてんしゅ","untenshu","driver","town","🚗"],
["パイロット","pairotto","pilot","town","🧑‍✈️"],
["うちゅうひこうし","uchuuhikoushi","astronaut","town","🧑‍🚀"],
["かしゅ","kashu","singer","town","🎤"],
["がか","gaka","painter","town","🎨"],
["シェフ","shefu","chef","town","🧑‍🍳"],
["バレーボール","bareebooru","volleyball","fun","🏐"],
["バドミントン","badominton","badminton","fun","🏸"],
["たっきゅう","takkyuu","table tennis","fun","🏓"],
["ドッジボール","dojjibooru","dodgeball","fun","🥎"],
["スキー","sukii","skiing","fun","⛷️"],
["スケート","sukeeto","ice skating","fun","⛸️"],
["たいそう","taisou","gymnastics","fun","🤸"],
["からて","karate","karate","fun","🥋"],
["じゅうどう","juudou","judo","fun","🥋"],
["けんどう","kendou","kendo","fun","🤺"],
["ゴルフ","gorufu","golf","fun","⛳"],
["ウニ","uni","sea urchin","sea","🦔"],
["マグロ","maguro","tuna","sea","🐟"],
["サケ","sake","salmon","sea","🐟"],
["ふぐ","fugu","pufferfish","sea","🐡"],
["ウミガメ","umigame","sea turtle","sea","🐢"],
["アシカ","ashika","sea lion","sea","🦭"],
["サンゴ","sango","coral","sea","🪸"],
["かいそう","kaisou","seaweed","sea","🌿"],
["かもめ","kamome","seagull","sea","🐦"],
["サーフィン","saafin","surfing","sea","🏄"],
["うめ","ume","plum blossom","nature","💮"],
["あさがお","asagao","morning glory","nature","🌺"],
["あじさい","ajisai","hydrangea","nature","💠"],
["もみじ","momiji","maple leaves","nature","🍁"],
["いちょう","ichou","ginkgo","nature","🍂"],
["サボテン","saboten","cactus","nature","🌵"],
["まつのき","matsunoki","pine tree","nature","🌲"],
["しま","shima","island","nature","🏝️"],
["ちきゅう","chikyuu","Earth","nature","🌍"],
["れいぞうこ","reizouko","fridge","home","🧊"],
["せんたくき","sentakuki","washing machine","home","🫧"],
["でんしレンジ","denshirenji","microwave","home","⏲️"],
["そうじき","soujiki","vacuum","home","🧹"],
["かいだん","kaidan","stairs","home","🪜"],
["エアコン","eakon","air conditioner","home","❄️"],
["ストーブ","sutoobu","heater","home","🔥"],
["ごみばこ","gomibako","trash can","home","🗑️"],
["かぎ","kagi","key","home","🔑"],
["ほんだな","hondana","bookshelf","home","📚"],
["カーテン","kaaten","curtain","home","🪟"],
["シャンプー","shanpuu","shampoo","home","🧴"],
["せっけん","sekken","soap","home","🧼"],
["パンツ","pantsu","underwear","clothes","🩲"],
["サンダル","sandaru","sandals","clothes","🩴"],
["ブーツ","buutsu","boots","clothes","👢"],
["レインコート","reinkooto","raincoat","clothes","🧥"],
["エプロン","epuron","apron","clothes","🧑‍🍳"],
["ネックレス","nekkuresu","necklace","clothes","📿"],
["ゆびわ","yubiwa","ring","clothes","💍"],
["リボン","ribon","ribbon","clothes","🎀"],
["ゆかた","yukata","summer kimono","clothes","👘"],
["きもの","kimono","kimono","clothes","👘"],
["あめがふる","ame ga furu","it's raining","weather","🌧️"],
["ゆきがふる","yuki ga furu","it's snowing","weather","🌨️"],
["かぜがふく","kaze ga fuku","wind is blowing","weather","🌬️"],
["はれる","hareru","to clear up","weather","🌤️"],
["くもる","kumoru","to get cloudy","weather","🌥️"],
["てんきよほう","tenkiyohou","weather forecast","weather","📡"],
["つらら","tsurara","icicle","weather","❄️"],
["いなずま","inazuma","lightning","weather","⚡"],
["ひょう","hyou","hail","weather","🧊"],
["すきやき","sukiyaki","sukiyaki","food","🍲"],
["しゃぶしゃぶ","shabushabu","shabu-shabu","food","🍲"],
["おでん","oden","oden","food","🍢"],
["どんぶり","donburi","rice bowl","food","🍚"],
["なっとう","nattou","natto","food","🫘"],
["とうふ","toufu","tofu","food","⬜"],
["うめぼし","umeboshi","pickled plum","food","🔴"],
["もち","mochi","rice cake","food","🍡"],
["だんご","dango","sweet dumpling","food","🍡"],
["たいやき","taiyaki","taiyaki","food","🐟"],
["かきごおり","kakigoori","shaved ice","food","🍧"],
["わたあめ","wataame","cotton candy","food","🍭"],
["ゼリー","zerii","jelly","food","🍮"],
["ヨーグルト","yooguruto","yogurt","food","🥛"],
["スパゲッティ","supagetti","spaghetti","food","🍝"],
["ミルクティー","mirukutii","milk tea","drinks","🫖"],
["いちごミルク","ichigomiruku","strawberry milk","drinks","🍓"],
["サイダー","saidaa","soda pop","drinks","🥤"],
["りんごジュース","ringojuusu","apple juice","drinks","🧃"],
["きみどり","kimidori","yellow-green","colors","💚"],
["こん","kon","navy blue","colors","🟦"],
["ももいろ","momoiro","peach pink","colors","🌸"],
["カラフル","karafuru","colorful","colors","🌈"],
["チーター","chiitaa","cheetah","animals","🐆"],
["トカゲ","tokage","lizard","animals","🦎"],
["ハト","hato","pigeon","animals","🕊️"],
["カラス","karasu","crow","animals","🐦‍⬛"],
["せみ","semi","cicada","animals","🦗"],
["ほたる","hotaru","firefly","animals","✨"],
["とんぼ","tonbo","dragonfly","animals","❔"],
["くわがた","kuwagata","stag beetle","animals","🪲"],
["カマキリ","kamakiri","praying mantis","animals","🦗"],
["だんごむし","dangomushi","pill bug","animals","🐞"],
["ミミズ","mimizu","earthworm","animals","🪱"],
["モルモット","morumotto","guinea pig","animals","🐹"],
["みがく","migaku","to brush","verbs","🪥"],
["なでる","naderu","to pet","verbs","🐱"],
["だっこする","dakkosuru","to cuddle","verbs","🫂"],
["あくびする","akubisuru","to yawn","verbs","🥱"],
["びっくりする","bikkurisuru","to be surprised","verbs","😲"],
["わくわくする","wakuwakusuru","to be excited","verbs","🤩"],
["うまれる","umareru","to be born","verbs","🐣"],
["そだてる","sodateru","to grow","verbs","🌱"],
["さく","saku","to bloom","verbs","🌸"],
["ひかる","hikaru","to shine","verbs","✨"],
["ころぶ","korobu","to fall down","verbs","💫"],
["なおす","naosu","to fix","verbs","🔧"],
["たいへん","taihen","tough","adjectives","😫"],
["かんたん","kantan","easy","adjectives","👌"],
["むずかしい","muzukashii","difficult","adjectives","😓"],
["たいせつ","taisetsu","important","adjectives","💖"],
["とくべつ","tokubetsu","special","adjectives","🌟"],
["ふしぎ","fushigi","mysterious","adjectives","🔮"],
["あぶない","abunai","dangerous","adjectives","⚠️"],
["あんぜん","anzen","safe","adjectives","🛟"],
["べんり","benri","handy","adjectives","🧰"],
["じょうず","jouzu","good at","adjectives","👏"],
["へた","heta","bad at","adjectives","😅"],
["ひま","hima","bored","adjectives","🥱"],
["しんせつ","shinsetsu","helpful","adjectives","🤗"],
["ゆうめい","yuumei","famous","adjectives","🏆"],
["おかしい","okashii","silly","adjectives","😜"],
["へん","hen","weird","adjectives","🤪"],
["きたない","kitanai","dirty","adjectives","🗑️"],
["せまい","semai","cramped","adjectives","📦"],
["ひろい","hiroi","spacious","adjectives","🏞️"],
["まるい","marui","round","adjectives","⚪"],
["しかくい","shikakui","square","adjectives","⬜"],
["ふかい","fukai","deep","adjectives","🌊"],
["とおい","tooi","far","adjectives","🔭"],
["ちかい","chikai","near","adjectives","📍"],
["おなじ","onaji","same","adjectives","🟰"],
["じゅぎょう","jugyou","class","school","🏫"],
["こうちょうせんせい","kouchousensei","principal","school","👔"],
["ほけんしつ","hokenshitsu","nurse's office","school","🩹"],
["たいいくかん","taiikukan","gym","school","🏟️"],
["うんどうじょう","undoujou","sports field","school","🏃"],
["プール","puuru","pool","school","🏊"],
["もんだい","mondai","question","school","❓"],
["こたえ","kotae","answer","school","💡"],
["せいと","seito","student","school","🧑‍🎓"],
["いちねんせい","ichinensei","first grader","school","1️⃣"],
["にねんせい","ninensei","second grader","school","2️⃣"],
["じしょ","jisho","dictionary","school","📔"],
["ちず","chizu","map","school","🗺️"],
["せんしゅ","senshu","athlete","town","🏅"],
["びようし","biyoushi","hairdresser","town","💇"],
["のうか","nouka","farmer","town","🚜"],
["かがくしゃ","kagakusha","scientist","town","🧑‍🔬"],
["しごと","shigoto","job","town","💼"],
["カフェ","kafe","cafe","town","☕"],
["ポスト","posuto","mailbox","town","📪"],
["ガソリンスタンド","gasorinsutando","gas station","town","⛽"],
["おしろ","oshiro","castle","town","🏰"],
["こうばん","kouban","police box","town","👮"],
["いちば","ichiba","market","town","🛒"],
["くうこう","kuukou","airport","transport","🛫"],
["みなと","minato","harbor","transport","⚓"],
["ボート","booto","rowboat","transport","🚣"],
["バイク","baiku","motorbike","transport","🏍️"],
["スクールバス","sukuurubasu","school bus","transport","🚌"],
["ベビーカー","bebiikaa","stroller","transport","👶"],
["キックボード","kikkuboodo","kick scooter","transport","🛴"],
["スケートボード","sukeetoboodo","skateboard","transport","🛹"],
["バイオリン","baiorin","violin","fun","🎻"],
["フルート","furuuto","flute","fun","🎶"],
["トランペット","toranpetto","trumpet","fun","🎺"],
["リコーダー","rikoodaa","recorder","fun","🎵"],
["トランプ","toranpu","playing cards","fun","🃏"],
["ヨーヨー","yooyoo","yo-yo","fun","🪀"],
["けんだま","kendama","kendama","fun","🎯"],
["こま","koma","spinning top","fun","🌀"],
["たこあげ","takoage","kite flying","fun","🪁"],
["しゃぼんだま","shabondama","soap bubbles","fun","🫧"],
["ぬりえ","nurie","coloring book","fun","🖍️"],
["えほん","ehon","picture book","fun","📖"],
["キャンプ","kyanpu","camping","fun","🏕️"],
["つり","tsuri","fishing","fun","🎣"],
["クイズ","kuizu","quiz","fun","❓"],
["なぞなぞ","nazonazo","riddle","fun","🤔"],
["ハロウィン","harowin","Halloween","fun","🎃"],
["クリスマス","kurisumasu","Christmas","fun","🎄"],
["じめん","jimen","ground","nature","🟫"],
["つち","tsuchi","soil","nature","🟤"],
["ねっこ","nekko","root","nature","🌱"],
["みずたまり","mizutamari","puddle","nature","💧"],
["さばく","sabaku","desert","nature","🏜️"],
["どうくつ","doukutsu","cave","nature","🕳️"],
["おんせん","onsen","hot spring","nature","♨️"],
["うちゅう","uchuu","outer space","nature","🌌"],
["コスモス","kosumosu","cosmos flower","nature","🌼"],
["やめる","yameru","to quit","verbs","🛑"],
["つづける","tsuzukeru","to continue","verbs","🔁"],
["かんがえる","kangaeru","to think","verbs","🤔"],
["あつめる","atsumeru","to collect","verbs","🧺"],
["ならべる","naraberu","to line up","verbs","🧱"],
["かぞえる","kazoeru","to count","verbs","🔢"],
["はかる","hakaru","to measure","verbs","📐"],
["まぜる","mazeru","to mix","verbs","🥄"],
["やく","yaku","to bake","verbs","🍳"],
["おる","oru","to fold","verbs","🦢"],
["ぬる","nuru","to paint","verbs","🖌️"],
["うごく","ugoku","to move","verbs","🌀"],
["まがる","magaru","to turn","verbs","↪️"],
["わたる","wataru","to cross","verbs","🚸"],
["ごぜん","gozen","a.m.","time","🕗"],
["ごご","gogo","p.m.","time","🕑"],
["おととい","ototoi","day before yesterday","time","⏪"],
["あさって","asatte","day after tomorrow","time","⏩"],
["こんしゅう","konshuu","this week","time","🗓️"],
["せんしゅう","senshuu","last week","time","⬅️"],
["ことし","kotoshi","this year","time","📅"],
["きょねん","kyonen","last year","time","⏪"],
["らいねん","rainen","next year","time","⏩"],
["まいあさ","maiasa","every morning","time","🌅"],
["おしょうがつ","oshougatsu","New Year","time","🎍"],
["なつやすみ","natsuyasumi","summer vacation","time","🏖️"],
["ふゆやすみ","fuyuyasumi","winter vacation","time","⛄"],
["ふん","fun","minute","time","⏱️"],
["びょう","byou","second","time","⏱️"],
["ひとり","hitori","one person","numbers","🧍"],
["ふたり","futari","two people","numbers","👫"],
["いっぴき","ippiki","one animal","numbers","🐾"],
["さんびき","sanbiki","three animals","numbers","🐈"],
["いちまい","ichimai","one sheet","numbers","📄"],
["いっぽん","ippon","one long thing","numbers","🥖"],
["いっさい","issai","one year old","numbers","1️⃣"],
["はっさい","hassai","eight years old","numbers","8️⃣"],
["はんぶん","hanbun","half","numbers","🌗"],
["ペット","petto","pet","family","🐾"],
["しんせき","shinseki","relatives","family","👨‍👩‍👧"],
["コロッケ","korokke","croquette","food","🍘"],
["キウイ","kiui","kiwi","food","🥝"],
["マンゴー","mangoo","mango","food","🥭"],
["ブルーベリー","buruuberii","blueberry","food","🫐"],
["さつまいも","satsumaimo","sweet potato","food","🍠"],
["なす","nasu","eggplant","food","🍆"],
["ピーマン","piiman","bell pepper","food","🫑"],
["ほうれんそう","hourensou","spinach","food","🥬"],
["キャベツ","kyabetsu","cabbage","food","🥬"],
["だいこん","daikon","radish","food","⬜"],
["えだまめ","edamame","edamame","food","🫛"],
["くだもの","kudamono","fruit","food","🍎"],
["やさい","yasai","vegetables","food","🥦"],
["おやつ","oyatsu","snack time","food","🍪"],
["はじめまして","hajimemashite","nice to meet you","phrases","🤝"],
["よろしくおねがいします","yoroshiku onegaishimasu","please be kind","phrases","🙇"],
["ひさしぶり","hisashiburi","long time no see","phrases","🤗"],
["おだいじに","odaiji ni","get well soon","phrases","🤒"],
["これはなんですか","kore wa nan desu ka","what is this?","phrases","❓"],
["トイレはどこですか","toire wa doko desu ka","where is the toilet?","phrases","🚽"],
["いくらですか","ikura desu ka","how much is it?","phrases","💰"],
["わかりません","wakarimasen","I don't understand","phrases","😕"],
["わかりました","wakarimashita","got it","phrases","🫡"],
["できました","dekimashita","I did it","phrases","🙌"],
["みてみて","mite mite","look, look!","phrases","👀"],
["どうしたの","doushita no","what's wrong?","phrases","😟"],
["きもち","kimochi","feeling","phrases","💗"]
];
